platform :osx, '10.12'

target 'Log4SwiftTestApp' do
  use_frameworks!
  pod 'Log4swift', :path => '../..'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.1'
        end
    end
end